/**
 * @description Utility Class Constant Value
 */
public with sharing class U_Constants {

    /* General */
    public static final String COUNTRY_FRANCE = 'France';
    public static final String COUNTRY_GERMANY = 'Germany';
    public static final String COUNTRY_ITALY = 'Italy';
    public static final String COUNTRYCODE_FRANCE = 'FR';
    public static final String COUNTRYCODE_GERMANY = 'DE';
    public static final String COUNTRYCODE_ITALY = 'IT';

    /* Products */
    public static final String PRODUCT_TRIGRAM_PDT1 = 'PDT1';
    public static final String PRODUCT_TRIGRAM_PDT2 = 'PDT2';
    public static final String PRODUCT_TRIGRAM_PDT3 = 'PDT3';

    /* Chat Transcript */
    public static final String LIVECHATTRANSCRIPT_STATUS_COMPLETED ='Completed';
    public static final String LIVECHATTRANSCRIPT_STATUS_MISSED = 'Missed';
}